[[main]]
identifier = "julia Dojo"
name = "Julia Dojo"
url = "/vi/posts/julia-dojo/intro"
weight = 5
pluralizelisttitles = false

[[main]]
identifier = "about"
name = "Giới thiệu"
url = "about"
weight = 1
