[[main]]
identifier = "lyx"
name = "LyX"
url = "/series/lyx/"
weight = 5

[[main]]
identifier = "julia Dojo"
name = "Julia Dojo"
url = "/julia-dojo"
weight = 5

[[main]]
identifier = "about"
name = "Giới thiệu"
url = "/about"
weight = 1

[[main]]
identifier = "contact-vi"
name = "Liên hệ"
url = "/lien-he/"
weight = 2

