language: shell
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb

branch:
  only:
    - gh-pages

script:
  - ./deploy.sh

env:
  global:
    - HUGO_VERSION=0.69.2

notifications:
  email: false
