baseURL = "/"
languageCode = "vi-vn"
title = "#Rants"
theme = "mainroad"

[Author]
name = "Hùng"

[Params]
subtitle = "Blog cá nhân, ranting, moaning, abc xyz..."
readmore = true
readMore = "Đọc thêm"
post_navigation = true

[Params.sidebar]
home = "right"
list = "left"
single = false
widgets = ["recent", "taglist", "categories"]

[Params.widgets]
recent_num = 8
tags_counter = true

[Params.widgets.social]
github = "ndgnuh"
email = "ndgnuh@protonmail.com"

